### ISSUE TITLE
installation on version-12 frappe/ERPNext fails

### ISSUE THREAD

**Issue by dulhaver** [aerele/apparelo#115]
I tried to install apparelo on a version-12 instance of frappe/erpnext (running in `/opt/bench/`)
```
cd frappe-bench
bench get-app apparelo https://github.com/aerele/apparelo
bench --site [site-name] install-app apparelo
```
and fail with the below error

```
:~/frappe-bench$ bench --site [site-name] install-app apparelo

Installing apparelo...
Updating DocTypes for apparelo      : [===============                         ]Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/commands/site.py", line 173, in install_app
    _install_app(app, verbose=context.verbose)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/installer.py", line 82, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/sync.py", line 56, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 66, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 141, in import_doc
    doc.insert()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_post_save_methods()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 919, in run_post_save_methods
    self.run_method("on_update")
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 299, in on_update
    self.run_module_method("on_doctype_update")
  File "/opt/bench/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 368, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 814, in get_module
    return importlib.import_module(modulename)
  File "/opt/bench/frappe-bench/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/bench/frappe-bench/apps/apparelo/apparelo/apparelo/doctype/dc/dc.py", line 17
    abbr = frappe.db.get_value("Company",f"{default_company}","abbr")
                                                            ^
SyntaxError: invalid syntax
```

can't make much of that though. Maybe it gives you a hint of what is going wrong

**Comment by M0hammedHaris** [comment]
Hi @vrms 
It seems that you are using python 3.5, as ```f string ``` is supported from python 3.6 and above.
**Apparelo** needs python 3.6 or above to run.

**Comment by karthikeyan5** [comment]
@vrms, you also need to complete the setup wizard of ERPNext before you install this app. 

The installation instructions and the requirements have now been updated in the readme. Please refer to it.

Thanks for reporting this error.

**Comment by dulhaver** [comment]
it's an existing instance, so the setup is finished. I'll update python and report back how it goes
