### ISSUE TITLE
DocType Global Defaults not found

### ISSUE THREAD

**Issue by R4tt3xx** [aerele/apparelo#220]
Good Day..

I am having an issue installing the version 13 branch. Below is the error log..

'Updating DocTypes for apparelo      : [                    ] 1%An error occurred while installing apparelo: DocType Global Defaults not found
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 186, in install_app
    sync_for(name, force=True, sync_everything=True, verbose=verbose, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 75, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1243, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 376, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 435, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 238, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1200, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/apparelo/apparelo/apparelo/doctype/lot_creation/lot_creation.py", line 103, in <module>
    default_company = frappe.db.get_single_value('Global Defaults', 'default_company')
  File "apps/frappe/frappe/database/database.py", line 678, in get_single_value
    df = frappe.get_meta(doctype).get_field(fieldname)
  File "apps/frappe/frappe/__init__.py", line 1106, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "apps/frappe/frappe/model/meta.py", line 49, in get_meta
    meta = Meta(doctype)
  File "apps/frappe/frappe/model/meta.py", line 106, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "apps/frappe/frappe/model/document.py", line 118, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/meta.py", line 111, in load_from_db
    super(Meta, self).load_from_db()
  File "apps/frappe/frappe/model/document.py", line 163, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType Global Defaults not found'

Is there anything that I can do in order to resolve this issue ?

**Comment by R4tt3xx** [comment]
Fixed it ...
